name: Capture Frame and Upload Image

on:
  push:
    branches:
      - main  # Replace 'main' with your repository's default branch if it's different

jobs:
  capture_frame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: sudo apt-get install python3-pip && pip install yt-dlp

      - name: Capture Frame
        run: ffmpeg -i "$(yt-dlp -g url | head -n 1)" -vframes 1 capture.jpg

      - name: Commit and Push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add capture.jpg
          git commit -m "Captured frame"
          git push
